### ISSUE TITLE
ERROR: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by grtjn** [marklogic/roxy#620] opened 2016-06-20 12:07 UTC
Running `ml dev info` when `deploy/dev.properties` does not exist results in `ERROR: no implicit conversion of nil into String`. Line 131 of `server_config.rb` should read:

```
        logger.info k + ": " + v.to_s
```

(e.g. with an extra `.to_s` after v)

**Comment by grtjn** [comment] 2016-06-20 12:08
Note: `ml dev info --format=json` works fine..

**Comment by grtjn** [comment] 2016-06-20 12:09
PS: my impression was that it breaks on `ml.server` being not properly set..

**Comment by RobertSzkutak** [comment] 2016-08-23 15:08
Looks like a duplicate of issue #224

**Comment by dmcassel** [comment] 2016-10-27 20:48
fixed in dev

**Closed by dmcassel** 2016-10-27 20:48 UTC
Labels: bug, duplicate
