### ISSUE TITLE
How to load data into specific collection?

### ISSUE THREAD

**Issue by trekvr** [marklogic/roxy#712] opened 2017-01-04 12:37 UTC
Hi,

How to load data into specific collection? tried below command but not working.

cmd:
ml local deploy content --collection=abc

Regards,
Rajesh

**Comment by dmcassel** [comment] 2017-01-04 14:57
`--collection` is not supported on that command. You can see the options for any command by adding the `-h` flag:

    ml deploy content -h

Our recommendation is to use MLCP (`ml mlcp -h`). Note that MLCP is not included in the Roxy distribution; set the `mlcp-home` property to point to where you have MLCP installed. 

If someone wanted to add the `--collection` parameter, a PR would be welcome.

**Comment by RobertSzkutak** [comment] 2017-01-04 15:11
Duplicate of https://github.com/marklogic/roxy/issues/106

It's definitely preferable to use MLCP, but I recognize the attractive convenience of such a feature.

**Comment by dmcassel** [comment] 2017-01-04 16:10
closing as duplicate

**Closed by dmcassel** 2017-01-04 16:10 UTC
Labels: deployer, duplicate, enhancement
