### ISSUE TITLE
Deployer error with ruby 2.1.0

### ISSUE THREAD

**Issue by jmakeig** [marklogic/roxy#179] opened 2014-01-27 22:16 UTC
README says 1.9.3+. Does this apply only to the 1.x major version? Here's what happens when I run just the `ml` command with Ruby 2.1.0 on OS X.

```
./ml
/usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- openssl (LoadError)
	from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/2.1.0/net/https.rb:22:in `<top (required)>'
	from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/jmakeig/Workspaces/roxy/deploy/lib/RoxyHttp.rb:23:in `<top (required)>'
	from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/jmakeig/Workspaces/roxy/deploy/lib/server_config.rb:20:in `<top (required)>'
	from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from deploy/lib/ml.rb:17:in `<main>'
```

**Comment by grtjn** [comment] 2015-07-07 15:17
I ran a test with a centos vm that runs ruby 2.1.6, works just fine. It seems to be an issue with Ruby 2.1.0 on Mac:

http://stackoverflow.com/questions/21201493/couldnt-require-openssl-in-ruby

Close this issue?

**Comment by Thijxx** [comment] 2015-08-04 18:55
Please keep open. Same issue with Ruby 2.2 on CentOS 6.6
Did not find any workaround so far.

**Comment by rlouapre** [comment] 2015-08-05 14:38
No issues from Windows 7 with Ruby 2.2.1

**Comment by grtjn** [comment] 2015-08-17 13:51
@Thijxx any hints on how to reproduce your setup?

**Comment by Thijxx** [comment] 2015-08-25 13:43
Yes. Install CentOS 6.6, install Ruby 2.2 and then run Roxy.
Guess Ruby needs something for OpenSSL and thats also not in the repo for CentOS 6 so it's a 'build from source' spiral.

**Comment by grtjn** [comment] 2015-08-28 05:02
I need a little more detail on install centos and ruby. Did you do that in a vm, and how? I typically use a pre-installed vm distribution, and there are so many flavors. Maybe send me details offline?

You could also try to reproduce this with mlvagrant, I have made quite some improvements this week, and it now supports centos 6.5, 6.6, 7.0, and 7.1. That would make it easier for me to mimic your steps, and try to reproduce..

**Comment by Thijxx** [comment] 2015-08-30 19:04
It was a CentOS 6.6 minimal installation by ISO in VirtualBox. Installation was done from source with make install etc. since the CentOS 6 repo can't provide the latest ruby, it's at 1.9.something I guess. But I noticed there are more packages needed than just the ruby package.

**Comment by dmcassel** [comment] 2015-08-31 18:57
@Thijxx it looks like your build didn't include openssl. From [askubuntu](http://askubuntu.com/questions/261914/install-ruby-2-0-with-openssl-and-readline-support), 

> In your source location, cd ext/openssl and then ruby extconf.rb. This will generate a makefile in the ext/openssl directory. Simply make && sudo make install it to build the ruby openssl extension, and install the .so into the appropriate location.

> Then you should be able to make ruby properly.

**Comment by grtjn** [comment] 2015-09-01 14:24
For the record, this seems a good method for installing latest Ruby (using rvm). openssl is listed in at least one of the commands:

http://tecadmin.net/install-ruby-2-1-on-centos-rhel/

**Comment by heelix** [comment] 2015-09-01 14:33
This will set up the current stable, which is 2.2.4(something)

# yum groupinstall "Development Tools"
# yum install openssl-devel
# wget http://cache.ruby-lang.org/pub/ruby/stable-snapshot.tar.gz
# tar xvfvz stable-snapshot.tar.gz
# cd stable-snapshot
# ./configure
# make
# make install
# ruby -v

**Comment by seongbae-ml** [comment] 2015-09-05 15:26
@dmcassel I'm suspecting it was upgrade to 10.10 Yosemite that broke my ruby with openssl.

**Comment by seongbae-ml** [comment] 2015-09-05 17:33
@dmcassel I reinstalled ruby following instructions from https://gorails.com/setup/osx/10.10-yosemite and I can run ml fine now.

**Comment by grtjn** [comment] 2015-09-17 21:33
Pushing away for the moment..

**Comment by dmcassel** [comment] 2016-10-25 14:23
It sounds like Roxy is working as long as ssl is compiled in, so closing. If anyone has trouble with a version of Ruby that does have openssl, please open a new issue with the Ruby version and platform.

**Closed by dmcassel** 2016-10-25 14:23 UTC
Labels: bug
