### ISSUE TITLE
wipe does not remove test content db

### ISSUE THREAD

**Issue by joecrean** [marklogic/roxy#578] opened 2016-03-06 12:10 UTC
Running ml <env> wipe does not remove the test-content db...

**Comment by dmcassel** [comment] 2016-03-08 18:49
@joecrean I'm unable to reproduce this using current code on the dev branch. What branch and how current is your Roxy code? What version of ML? What platform? 

Please confirm that Roxy sees the properties related to testing:

    $ ./ml local info | grep test

> ml.do-not-deploy-tests: prod
ml.test-content-db: roxy-content-test
ml.test-port: 8043
ml.xquery-test.dir: /Users/dcassel/git/roxy-dmc/src/test

**Comment by joecrean** [comment] 2016-03-13 12:49
My bad - very bad...
The version of Roxy is 1.7.2 (a release cloned from github).
The platform is Windows 2008 R2.

When i run ``ml dev info|grep test`` I see 

```
~/Workspace/Thieme/ps-src-main/core-services/trunk -> ml dev info | grep test
ml.xquery-test.dir: /Users/jcrean/Workspace/Thieme/ps-src-main/core-services/trunk/src/test
ml.test-port: 8042
ml.test-modules-db: PS-modules
ml.test-content-db: PS-content-test
ml.do-not-deploy-tests: prod
```

Please note I am running the command on my laptop pointing it to the Windows based ``dev`` env.
The windows machine itself does not have ``ruby`` installed. I deploy to it from a windows based build machine and use ``java -jar roxy.jar <roxy command here>`` to deploy to this dev env.

**Comment by dmcassel** [comment] 2016-10-18 14:48
Can anyone reproduce this with the current dev branch code?

**Comment by dmcassel** [comment] 2016-10-18 17:15
Closing as can't-reproduce. If someone can make this happen with the current dev branch code, please reopen.

**Closed by dmcassel** 2016-10-18 17:15 UTC
Labels: help wanted, unit testing
