### ISSUE TITLE
'filesystem' db created when when 'filesystem' is specified as the 'modules-db'?

### ISSUE THREAD

**Issue by JKesMc9tqIQe9M** [marklogic/roxy#329] opened 2015-01-05 00:20 UTC
When I specify 'filesystem' for the 'modules-db' and 'app-modules-db' config settings, Roxy seems to correctly point to the modules on the filesystem in the app server it creates. However it also seems to create a 'filesystem' database. This isn't making sense to me. Probably something I'm doing wrong here -- though I'm not finding a solution in the docs. Any help would be appreciated.

Thanks!

**Comment by grtjn** [comment] 2015-01-05 12:41
I am able to reproduce the issue with latest Roxy (dev). Let me take a closer look..

**Comment by grtjn** [comment] 2015-01-05 12:50
You can get round this by commenting or removing the modules database part in deploy/ml-config.xml.

Would be nice though if Roxy would either ignore creation of databases named 'filesystem', or would at least give some warning with a hint how to do it correctly..

**Comment by JKesMc9tqIQe9M** [comment] 2015-01-06 02:38
Hoi Geert, thanks for confirming you can reproduce it. It's not really a blocking problem for me, but I thought I'd report it. I think that Roxy should not create a 'filesystem' db if 'filesystem' is specified as the modules-db in the config. Seems like you agree. 

Also: what do you think about making a related modification so that if you are specifying 'filesystem', then the roxy 'deploy modules' command won't do anything -- and maybe instead prints a message to say that it won't do anything in these casess?

If you agree with these changes, would you like me to look into submitting a PR? Ideally it seems like Roxy should know how to work in these situations and the user should not need to modify the `ml-config.xml`.

Thanks again.

**Comment by grtjn** [comment] 2015-01-06 14:48
Using file-system with Roxy is not a very common thing, and in general I'd recommend not using file-system at all. I'd also say that Roxy makes using modules databases very easy. Note also that ml-config.xml *is* intended for user-editing. It makes perfect sense to remove the modules db part in case of running against file-system.

Having said that, it does make sense to make Roxy more robust. I'm not quite sure what happens if you try to deploy modules when using file-system. I guess the modules currently end up in the 'filesystem' database, which is of no use. It should at the least warn that you try to deploy to a database named 'filesystem'. Same during bootstrap, but providing feedback to end-user during bootstrap is a bit more tricky. In any case, it can't ignore the database silently for sure.

@paxtonhare @dmcassel : care to comment as well?

**Comment by rlouapre** [comment] 2015-01-06 15:30
It is useful to make sure Roxy ```deploy modules``` command skip when app-modules-db=filesystem.
I am frequently using a script to execute all roxy commands and it makes more sense to make changes ml roxy properties than the script itself.

Yes the modules currently end up in filesystem database.

**Comment by grtjn** [comment] 2015-01-21 07:56
Fixed in dev

**Closed by grtjn** 2015-01-21 07:56 UTC
