### ISSUE TITLE
Incorrect name for named replica forest

### ISSUE THREAD

**Issue by joeglorioso** [marklogic/roxy#745] opened 2017-02-14 19:22 UTC
When using a named forest for a forest replica in a cluster, the name of the generated forest includes an appendix "-on-002" where 002 is the number of the host in the cluster.

For example, the name of the replica in the below ml-config.xml is _forest-1r_, but when this is bootstrapped, the name of the forest is _forest-1r-on-002_.
```
<configuration>
  <assignments xmlns="http://marklogic.com/xdmp/assignments" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://marklogic.com/xdmp/assignments assignments.xsd">
    <assignment>
      <forest-name>forest-1r</forest-name>
    </assignment>
    <assignment>
      <forest-name>forest-1</forest-name>
      <replica-names>
        <replica-name>forest-1r</replica-name>
      </replica-names>
    </assignment>
  </assignments>
  <databases xmlns="http://marklogic.com/xdmp/database" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://marklogic.com/xdmp/database database.xsd">
    <database>
      <database-name>database</database-name>
      <forests>
        <forest-id>forest-1</forest-id>
      </forests>
    </database>
  </databases>
</configuration>
```
<img width="892" alt="screen shot 2017-02-14 at feb 14 2017 2 21 23 pm" src="https://cloud.githubusercontent.com/assets/1774146/22945097/0190ea14-f2c1-11e6-8790-36301410b915.png">

This is on an ml-vagrant generated Linux cluster, using MarkLogic 8.0-6 and the April-2017-dev version of Roxy.

**Comment by jamsilvia** [comment] 2017-02-15 18:04
I do not believe this to be an issue:

This is by design with the newer version of Roxy (post 1.7.5).  Added to Roxy was the ability to scale-out a previously bootstrapped and replicated cluster.  To make it easier to keep track of reassignment of replicas on scale out, and to avoid naming conflicts, the host number was added to the replica name.

e.g. this comes into play when you go from 3 nodes -> 5 nodes.  The replica for forest 3 is wrapped around and lives on forest 1 (e.g. forest-3r-on-001).  With the scale-out, the forest should live on node 4.  So the new roxy creates a forest3r-on-004 and marks the old forest-3r-on-001 for removal.  If the host number was not part of the forest name, there would be a time when "forest-3r" existed on both node 1 and node 4.

**Comment by joeglorioso** [comment] 2017-02-15 18:22
Thanks.  This is a good point.  I'm trying to replicate a client's existing configuration so this is a blocker.  Do you think that it would be possible to create a "proceed at your own risk" property to opt out of the naming convention?  If not, I will have to recommend moving to the Roxy naming convention.  I'll have to put some additional thought to this.  Let me know if you have a recommendation.

**Comment by jamsilvia** [comment] 2017-02-15 20:11
I can code in a flag to use the old naming convention - although I'd like to see people moving on to the new naming in case they were to scale out at some point.  So the flag should be used in cases like yours for trying to duplicate an old deployment (for debugging purposes), as opposed to a way to avoid the new names altogether moving forward.
I'll let @RobertSzkutak or @dmcassel make the final say.  I'm willing to code it.

**Closed** 2017-03-01 19:01 UTC
