### ISSUE TITLE
corb: Issue with passwords with non-alpha numeric characters

### ISSUE THREAD

**Issue by peetkes** [marklogic/roxy#148] opened 2013-10-21 20:32 UTC
Is there an issue with non alpha numerical characters in the password of the admin user?
I tried the corb part this evening, and it gave me an error because I had the pound sign (#) and the at-sign (@) in my password.

	ml local corb --uris=/corb/all-uri-selection.xqy --modules=/corb/add-collection.xqy
	java -cp /Users/peetkes/Private/git/my-hybrid/deploy/lib/java/corb.jar:/Users/peetkes/Private/git/my-hybrid/deploy/lib/java/marklogic-xcc-5.0.2.jar com.marklogic.developer.corb.Manager xcc://admin:admin@localhost:8051/my-hybrid-content "" corb/add-collection.xqy 1 corb/all-uri-selection.xqy "/" my-hybrid-modules false
	Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
	logging to CONSOLE
	Oct 21, 2013 7:27:39 PM com.marklogic.developer.SimpleLogger configureLogger
	INFO: setting up logging for: com.marklogic.ps
	Oct 21, 2013 7:27:39 PM com.marklogic.developer.corb.Manager run
	INFO: com.marklogic.developer.corb.Manager starting: version 2010-08-24.1 on 1.6.0_51 (Java(TM) SE Runtime Environment)
	Oct 21, 2013 7:27:39 PM com.marklogic.developer.corb.Manager run
	INFO: maximum heap size = 123 MiB
	Oct 21, 2013 7:27:39 PM com.marklogic.developer.corb.Manager prepareContentSource
	INFO: using content source xcc://admin:1#admin@@localhost:8051/my-hybrid-content
	Exception in thread "main" java.lang.IllegalArgumentException: Default provider - Not a usable net address: admin:1
		at com.marklogic.xcc.ContentSourceFactory.defaultConnectionProvider(ContentSourceFactory.java:340)
		at com.marklogic.xcc.ContentSourceFactory.newContentSource(ContentSourceFactory.java:214)
		at com.marklogic.xcc.ContentSourceFactory.newContentSource(ContentSourceFactory.java:163)
		at com.marklogic.xcc.ContentSourceFactory.newContentSource(ContentSourceFactory.java:182)
		at com.marklogic.developer.corb.Manager.prepareContentSource(Manager.java:357)
		at com.marklogic.developer.corb.Manager.run(Manager.java:232)
		at com.marklogic.developer.corb.Manager.main(Manager.java:198)

**Comment by grtjn** [comment] 2015-07-07 18:16
As mentioned by @rlouapre this seems to be a duplicate of #177, closing this issue..

**Closed by grtjn** 2015-07-07 18:16 UTC
Labels: bug
