### ISSUE TITLE
Framework tests fail using ssh tunnels

### ISSUE THREAD

**Issue by bradmann** [marklogic/roxy#189] opened 2014-03-13 18:54 UTC
It looks like if there's a mismatch between the port number your browser is hitting and the actual port the test appserver is running on, test:easy-url() returns the port your browser provides, rather than the correct port.

**Comment by grtjn** [comment] 2015-07-07 12:48
Bit old ticket, but would be helpful to know which tests fail. Might save us setup a tunnel to reproduce ourselves. The test-helper seems to rely on `xdmp:get-request-header("Host")`..

**Comment by bradmann** [comment] 2015-07-07 13:30
routing.xqy and site-index.xqy under "Framework Tests"

If you have a VM, just ssh to it using -L 10042:localhost:8042 and point your browser to http://localhost:10042/tests/

You may even be able to ssh to your local machine and reproduce, but I haven't attempted that to verify.

**Comment by grtjn** [comment] 2015-07-07 14:24
Yep, that worked. It fails because it takes the port number from the browser, but it is doing an http-get against 'localhost', which is executed server-side. It should really simply use `xdmp:get-request-port()`. That seems to solve this. I will do a PR..

**Comment by grtjn** [comment] 2015-09-17 21:32
Fixed in dev

**Closed by grtjn** 2015-09-17 21:32 UTC
Labels: bug
