### ISSUE TITLE
roxy.jar fails to run on 1.7.4

### ISSUE THREAD

**Issue by tternquist** [marklogic/roxy#705] opened 2016-11-22 23:54 UTC
When i attempt to run roxy with roxy.jar I get the following error
```

java -jar roxy.jar 
LoadError: no such file to load -- app_specific
  require at org/jruby/RubyKernel.java:956
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
   <main> at uri:classloader:/roxy/bin/roxy.rb:39
     load at org/jruby/RubyKernel.java:974
   <main> at uri:classloader:/META-INF/main.rb:1
  require at org/jruby/RubyKernel.java:956
   (root) at uri:classloader:/META-INF/main.rb:1
   <main> at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
ERROR: org.jruby.embed.EvalFailedException: (LoadError) no such file to load -- app_specific
```

Is there anything else I need to do here?
Thanks!

**Comment by RobertSzkutak** [comment] 2016-11-22 23:59
Did you build roxy.jar yourself or are you using the one on the release page?

**Comment by tternquist** [comment] 2016-11-22 23:59
The one on the release page

**Comment by RobertSzkutak** [comment] 2016-11-23 00:17
Confirmed I'm also seeing this. Seems to be failing on `require app_specific` in ml.rb . I'm investigating this..

**Comment by RobertSzkutak** [comment] 2016-11-23 00:24
Possibly related : https://github.com/marklogic/roxy/issues/659 . In the process of downgrading my packages to test...

**Comment by RobertSzkutak** [comment] 2016-11-23 00:34
I've updated the release with a working jar. Please give it a try.

**Comment by RobertSzkutak** [comment] 2016-11-23 19:51
I have updated our documentation to specify the version of Warbler needed to build the JAR. We have also pushed out a 1.7.4.1 release noting the updated JAR. Closing this issue and will make an effort sooner than later to investigate building Roxy with newer builds of Warbler.

**Closed by RobertSzkutak** 2016-11-23 19:51 UTC
