### ISSUE TITLE
capture modules-db results in ERROR: 757: unexpected token

### ISSUE THREAD

**Issue by joeg13** [marklogic/roxy#713] opened 2017-01-05 19:15 UTC
I'm receiving an ERROR: 757: unexpected token when trying to capture a modules database.  To replicate this, create a modules database on localhost named test-modules and insert a single module named /foo.xqy.  Create a new Roxy project and run the capture command from within the project.  I've tried this with both the master and dev branches.

$ ml local capture --modules-db=test-modules
Retrieving source from test-modules...
ERROR: 757: unexpected token at '--0e040f1aa62b4e54
Content-Type: text/plain
X-Primitive: string

/foo.xqy
--0e040f1aa62b4e54--
'
ERROR: ["/Users/jglorioso/Downloads/temp/deploy/lib/json/common.rb:148:in `parse'", "/Users/jglorioso/Downloads/temp/deploy/lib/json/common.rb:148:in `parse'", "/Users/jglorioso/Downloads/temp/deploy/lib/server_config.rb:1621:in `save_files_to_fs'", "/Users/jglorioso/Downloads/temp/deploy/lib/server_config.rb:1432:in `capture'", "deploy/lib/ml.rb:168:in `<main>'"]

**Comment by dmcassel** [comment] 2017-01-05 19:28
What does foo.xqy have in it? Did you insert it using "ml deploy modules" or some other way?

**Comment by joeg13** [comment] 2017-01-05 20:00
In this case, I just used xdmp:document-insert in qconsole.  

```
xquery version "1.0-ml";

let $module :=
document {
'declare namespace html = "http://www.w3.org/1999/xhtml";
<p>hello world</p>'
}
return xdmp:document-insert('/foo.xqy', $module)
```

I have tried this on a client's live Modules database and my local Modules database also.  In each case, I received the same error.  The foo.xqy was just an easily reproducible case for you to test.  

I don't have another readily available environment to test in.  I don't think it matters, but I'm on Mac running OSX 10.12.  As I mentioned, I tried both the master and dev branches of Roxy so I know that it is current.

**Comment by dmcassel** [comment] 2017-01-05 22:24
Forgot to ask: what version of MarkLogic? With that information, we should have enough to reproduce.

**Comment by joeg13** [comment] 2017-01-06 14:08
I'm sorry.  That should have been on my initial post.  I've tried this against Linux 8.0-6 and Mac 8.0-6.

**Comment by dmcassel** [comment] 2017-01-09 23:33
verified in 8.0-5.8 (Mac). Investigating.

**Comment by dmcassel** [comment] 2017-01-13 17:08
The reason for the problem is that we switched how we send requests to MarkLogic 8 (using /v1/eval instead of Query Console), but didn't update how we process the response. I'll work on fixing that.

**Comment by joeg13** [comment] 2017-01-13 17:26
Thanks for the update Dave. Any estimate on when you're schedule will allow you time to turn around a fix?

**Comment by dmcassel** [comment] 2017-01-13 18:01
Working on it today.

**Comment by dmcassel** [comment] 2017-01-13 19:21
@joeg13 I just sent a pull request with a fix. If you'd like to test it, that would be helpful.

**Comment by joeg13** [comment] 2017-01-16 16:23
I saw some additional conversation between you and Robert in the PR.  Please let me know how I can best assist in testing.

**Comment by dmcassel** [comment] 2017-01-17 12:07
@joeg13 the fix is now merged into the dev branch. Please test and reopen if you still see a problem.

**Closed by dmcassel** 2017-01-17 12:07 UTC
Labels: bug, capture

**Comment by joeg13** [comment] 2017-01-18 20:20
Thanks.  This is working as expected now.
